Feature/error code filter
rankmyapp/error-handler pull request #2
Opened 2020-03-17 19:34 UTC by Beleren

[TASK 673](https://rankmyapp.atlassian.net/browse/RANK-673) - Filtrar erros enviados ao sentry.

2020-03-17 20:06 UTC, PatrickRNG requested changes

2020-03-17 20:06 UTC, PatrickRNG commented on index.js
> +    return next(err);
Precisa do return?

2020-03-17 20:06 UTC, PatrickRNG commented on index.js
> +    return true;
E esse aqui tbm

2020-03-17 20:10 UTC, icarcal requested changes

2020-03-17 20:10 UTC, icarcal commented on index.js
> +const errorHandler = (blockList = []) => ({
utilizar um objeto, para que fique explicito o que o parâmetro faz
```suggestion
const errorHandler = ({ blockEvents = [] } = {}) => ({
```

2020-03-17 20:11 UTC, Beleren commented on index.js
> +    return next(err);
https://eslint.org/docs/rules/consistent-return

E acho que só chamando o `next` no if ele não vai sair da função e ainda vai executar o sentry.

2020-03-17 20:11 UTC, Beleren commented on index.js
> +    return true;
https://eslint.org/docs/rules/consistent-return

2020-03-17 20:31 UTC, Beleren commented on index.js
> +const errorHandler = (blockList = []) => ({
não entendi como isso deixaria mais explícito.

2020-03-17 20:35 UTC, Beleren commented on index.js
> +    return next(err);
na real que eu preciso arrumar o outro return...

2020-03-17 20:40 UTC, evertonoliveira1 commented on .vscode/launch.json
> +{
precisa versionar esse arquivo?

2020-03-17 20:40 UTC, evertonoliveira1 commented on index.js
>      debug(`service:error->${req.protocol + '://' + req.get('host') + req.originalUrl}-> enventId: ${eventId}`)('throws an error %o', err.message);
```suggestion
    debug(`service:error->${req.protocol + '://' + req.get('host') + req.originalUrl}-> eventId: ${eventId}`)('throws an error %o', err.message);
```

2020-03-17 20:40 UTC, evertonoliveira1 commented on index.js
>      debug(`service:error->${req.protocol + '://' + req.get('host') + req.originalUrl}-> enventId: ${eventId}`)('throws an error %o', err.message);
formatar melhor esse linha, ela está muito longa

2020-03-17 20:40 UTC, evertonoliveira1 commented on index.js
>      debug(`service:error->${origin}-> enventId: ${eventId}`)('throws an error %o', err.message);
```suggestion
    debug(`service:error->${origin}-> eventId: ${eventId}`)('throws an error %o', err.message);
```

2020-03-17 20:42 UTC, Beleren commented on .vscode/launch.json
> +{
Acredito que é mais intuitivo pra quem quiser rodar e/ou debuger via VSCode em vez de ficar criando a config toda hora.

2020-03-17 20:43 UTC, Beleren commented on index.js
>      debug(`service:error->${req.protocol + '://' + req.get('host') + req.originalUrl}-> enventId: ${eventId}`)('throws an error %o', err.message);
https://github.com/rankmyapp/error-handler/pull/2/commits/47e39d7d9f023257deaf18707e946a15eabf172c

2020-03-17 20:43 UTC, Beleren commented on index.js
>      debug(`service:error->${origin}-> enventId: ${eventId}`)('throws an error %o', err.message);
https://github.com/rankmyapp/error-handler/pull/2/commits/47e39d7d9f023257deaf18707e946a15eabf172c

2020-03-17 20:43 UTC, Beleren commented on index.js
> +const errorHandler = (blockList = []) => ({
https://github.com/rankmyapp/error-handler/pull/2/commits/104add7c07a06641d548c4b5b12b55b7c65c80d3

2020-03-17 20:46 UTC, evertonoliveira1 commented on .vscode/launch.json
> +{
ok

2020-03-17 20:48 UTC, evertonoliveira1 commented on index.js
> +    debug(
const origin = `service:error->${req.protocol}://${req.get('host')}${req.originalUrl}->eventId: ${eventId}`;
debug(origin)('throws an error %o', err.message);

2020-03-17 20:49 UTC, evertonoliveira1 commented on index.js
> +      `service:error->${req.protocol +
```suggestion
     const origin = service:error->${req.protocol}://${req.get('host')}${req.originalUrl}->eventId: ${eventId};
debug(origin)('throws an error %o', err.message);
```

2020-03-17 20:58 UTC, Beleren commented on index.js
> +      `service:error->${req.protocol +
63f3f79

2020-03-17 20:59 UTC, Beleren commented
Só queria falar que fiquei feliz que vcs desseram a lenha no código, espero mais reviews assim.

2020-03-17 21:07 UTC, PatrickRNG commented on index.js
> +    return next(err);
Tava falando do último next fora do if mesmo.
Mas o comsistent return faz sentido mesmo, apesar de não usar o valor para nada.

2020-03-17 21:10 UTC, PatrickRNG submitted a review, later dismissed
👍 Boa

2020-03-18 14:28 UTC, PatrickRNG approved these changes

2020-03-18 14:43 UTC, evertonoliveira1 approved these changes
:+1:

2020-03-18 14:46 UTC, icarcal commented
🎉

2020-03-18 14:47 UTC, icarcal approved these changes
👏

2020-03-18 14:47 UTC, icarcal commented on index.js
> +const errorHandler = (blockList = []) => ({
Não é o nome da variável, mas sim a chamada.
O exemplo que você utiliza é o seguinte:

```javascript
errorHandler([401, 403, 404]).logError(origin, err500);
```

ficaria assim
```javascript
errorHandler({ blockEvents: [401, 403, 404] }).logError(origin, err500);
```

2020-03-18 14:47 UTC, merged